version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: tsbackend-pg
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tsbackend
    ports:
      - 49101:5432
    volumes:
      - D:\\var\\devops\\tsbackend\\postgres-data:/var/lib/postgresql/data
    networks:
      - tsbackend-net
  mongo:
    image: mongo
    container_name: tsbackend-mongo
    restart: always
    env_file:
      - .env
    ports:
      - 49104:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - D:\\var\\devops\\tsbackend\\mongo-data:/data/db
      - D:\\var\\devops\\tsbackend\\mongo-config:/data/configdb
    networks:
      - tsbackend-net

  queue:
    image: rabbitmq:3.11-management-alpine
    container_name: tsbackend-queue
    restart: always
    env_file:
      - .env
    hostname: queue-node
    labels:
      - io.portainer.accesscontrol.teams=tsbackend
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1234
    ports:
      - 49102:15672
      - 49103:5672
    networks:
      - tsbackend-net
    volumes:
      - D:\\var\\devops\\tsbackend\\queue-node/:/var/lib/rabbitmq/mnesia

networks:
  tsbackend-net:
    driver: bridge